// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/momoyo-droid/pismo/api/internal/model"
	"github.com/momoyo-droid/pismo/api/internal/service"
	"sync"
)

// Ensure, that AccountRepositoryMock does implement service.AccountRepository.
// If this is not the case, regenerate this file with moq.
var _ service.AccountRepository = &AccountRepositoryMock{}

// AccountRepositoryMock is a mock implementation of service.AccountRepository.
//
//	func TestSomethingThatUsesAccountRepository(t *testing.T) {
//
//		// make and configure a mocked service.AccountRepository
//		mockedAccountRepository := &AccountRepositoryMock{
//			CreateAccountFunc: func(ctx context.Context, account *model.Account) (*model.Account, error) {
//				panic("mock out the CreateAccount method")
//			},
//			GetAccountByIDFunc: func(ctx context.Context, accountID uint64) (*model.Account, error) {
//				panic("mock out the GetAccountByID method")
//			},
//		}
//
//		// use mockedAccountRepository in code that requires service.AccountRepository
//		// and then make assertions.
//
//	}
type AccountRepositoryMock struct {
	// CreateAccountFunc mocks the CreateAccount method.
	CreateAccountFunc func(ctx context.Context, account *model.Account) (*model.Account, error)

	// GetAccountByIDFunc mocks the GetAccountByID method.
	GetAccountByIDFunc func(ctx context.Context, accountID uint64) (*model.Account, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateAccount holds details about calls to the CreateAccount method.
		CreateAccount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Account is the account argument value.
			Account *model.Account
		}
		// GetAccountByID holds details about calls to the GetAccountByID method.
		GetAccountByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccountID is the accountID argument value.
			AccountID uint64
		}
	}
	lockCreateAccount  sync.RWMutex
	lockGetAccountByID sync.RWMutex
}

// CreateAccount calls CreateAccountFunc.
func (mock *AccountRepositoryMock) CreateAccount(ctx context.Context, account *model.Account) (*model.Account, error) {
	if mock.CreateAccountFunc == nil {
		panic("AccountRepositoryMock.CreateAccountFunc: method is nil but AccountRepository.CreateAccount was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Account *model.Account
	}{
		Ctx:     ctx,
		Account: account,
	}
	mock.lockCreateAccount.Lock()
	mock.calls.CreateAccount = append(mock.calls.CreateAccount, callInfo)
	mock.lockCreateAccount.Unlock()
	return mock.CreateAccountFunc(ctx, account)
}

// CreateAccountCalls gets all the calls that were made to CreateAccount.
// Check the length with:
//
//	len(mockedAccountRepository.CreateAccountCalls())
func (mock *AccountRepositoryMock) CreateAccountCalls() []struct {
	Ctx     context.Context
	Account *model.Account
} {
	var calls []struct {
		Ctx     context.Context
		Account *model.Account
	}
	mock.lockCreateAccount.RLock()
	calls = mock.calls.CreateAccount
	mock.lockCreateAccount.RUnlock()
	return calls
}

// GetAccountByID calls GetAccountByIDFunc.
func (mock *AccountRepositoryMock) GetAccountByID(ctx context.Context, accountID uint64) (*model.Account, error) {
	if mock.GetAccountByIDFunc == nil {
		panic("AccountRepositoryMock.GetAccountByIDFunc: method is nil but AccountRepository.GetAccountByID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AccountID uint64
	}{
		Ctx:       ctx,
		AccountID: accountID,
	}
	mock.lockGetAccountByID.Lock()
	mock.calls.GetAccountByID = append(mock.calls.GetAccountByID, callInfo)
	mock.lockGetAccountByID.Unlock()
	return mock.GetAccountByIDFunc(ctx, accountID)
}

// GetAccountByIDCalls gets all the calls that were made to GetAccountByID.
// Check the length with:
//
//	len(mockedAccountRepository.GetAccountByIDCalls())
func (mock *AccountRepositoryMock) GetAccountByIDCalls() []struct {
	Ctx       context.Context
	AccountID uint64
} {
	var calls []struct {
		Ctx       context.Context
		AccountID uint64
	}
	mock.lockGetAccountByID.RLock()
	calls = mock.calls.GetAccountByID
	mock.lockGetAccountByID.RUnlock()
	return calls
}
