// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/momoyo-droid/pismo/api/internal/model"
	"github.com/momoyo-droid/pismo/api/internal/service"
	"sync"
)

// Ensure, that TransactionRepositoryMock does implement service.TransactionRepository.
// If this is not the case, regenerate this file with moq.
var _ service.TransactionRepository = &TransactionRepositoryMock{}

// TransactionRepositoryMock is a mock implementation of service.TransactionRepository.
//
//	func TestSomethingThatUsesTransactionRepository(t *testing.T) {
//
//		// make and configure a mocked service.TransactionRepository
//		mockedTransactionRepository := &TransactionRepositoryMock{
//			CreateTransactionFunc: func(ctx context.Context, transaction *model.Transaction) (*model.Transaction, error) {
//				panic("mock out the CreateTransaction method")
//			},
//		}
//
//		// use mockedTransactionRepository in code that requires service.TransactionRepository
//		// and then make assertions.
//
//	}
type TransactionRepositoryMock struct {
	// CreateTransactionFunc mocks the CreateTransaction method.
	CreateTransactionFunc func(ctx context.Context, transaction *model.Transaction) (*model.Transaction, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateTransaction holds details about calls to the CreateTransaction method.
		CreateTransaction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Transaction is the transaction argument value.
			Transaction *model.Transaction
		}
	}
	lockCreateTransaction sync.RWMutex
}

// CreateTransaction calls CreateTransactionFunc.
func (mock *TransactionRepositoryMock) CreateTransaction(ctx context.Context, transaction *model.Transaction) (*model.Transaction, error) {
	if mock.CreateTransactionFunc == nil {
		panic("TransactionRepositoryMock.CreateTransactionFunc: method is nil but TransactionRepository.CreateTransaction was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Transaction *model.Transaction
	}{
		Ctx:         ctx,
		Transaction: transaction,
	}
	mock.lockCreateTransaction.Lock()
	mock.calls.CreateTransaction = append(mock.calls.CreateTransaction, callInfo)
	mock.lockCreateTransaction.Unlock()
	return mock.CreateTransactionFunc(ctx, transaction)
}

// CreateTransactionCalls gets all the calls that were made to CreateTransaction.
// Check the length with:
//
//	len(mockedTransactionRepository.CreateTransactionCalls())
func (mock *TransactionRepositoryMock) CreateTransactionCalls() []struct {
	Ctx         context.Context
	Transaction *model.Transaction
} {
	var calls []struct {
		Ctx         context.Context
		Transaction *model.Transaction
	}
	mock.lockCreateTransaction.RLock()
	calls = mock.calls.CreateTransaction
	mock.lockCreateTransaction.RUnlock()
	return calls
}
