basePath: /
definitions:
  handler.AccountRequest:
    properties:
      document_number:
        type: string
    required:
    - document_number
    type: object
  handler.AccountResponse:
    properties:
      account_id:
        type: integer
      document_number:
        type: string
    type: object
  handler.TransactionRequest:
    properties:
      account_id:
        type: integer
      amount:
        type: number
      operation_type_id:
        type: integer
    type: object
  handler.TransactionResponse:
    properties:
      account_id:
        type: integer
      amount:
        type: number
      operation_type_id:
        type: integer
      transaction_id:
        type: integer
    type: object
host: localhost:3000
info:
  contact: {}
  description: API for account and transaction management
  title: Pismo API
  version: "1.0"
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: Create a new account with the provided document number
      parameters:
      - description: Account creation payload
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/handler.AccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Account created successfully
          schema:
            $ref: '#/definitions/handler.AccountResponse'
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new account
      tags:
      - accounts
  /accounts/{id}:
    get:
      description: Retrieve account details by its ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Account fetched successfully
          schema:
            $ref: '#/definitions/handler.AccountResponse'
        "400":
          description: Invalid account ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Account not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get account by ID
      tags:
      - accounts
  /transactions:
    post:
      consumes:
      - application/json
      description: Create a new transaction with the provided account ID, operation
        type ID, and amount
      parameters:
      - description: Transaction creation payload
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.TransactionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Transaction created successfully
          schema:
            $ref: '#/definitions/handler.TransactionResponse'
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new transaction
      tags:
      - transactions
swagger: "2.0"
